<p>À la fin de la grande guerre, les peuples meurtris par le conflit cherchèrent à réparer les conséquences de ce dernier : reconstruction des bâtiments, soins des plus vulnérables, délimitation des terres, relance du commerce intérieur comme extérieur. Mais, de toutes ces problématiques, l'une d'entre elles s'imposa comme la plus urgente et la plus difficile à résoudre : la garantie d'une paix durable.</p>
<p>Si les alliances entre royaumes avaient démontré leurs failles, rester isolé n'était pas une solution, surtout à un moment de l'Histoire où l'entraide entre les peuples s'imposait pour que chacun puisse subsister. Un leader charismatique et unanime devait réussir à organiser ce renouveau et instaurer une nouvelle ère, tantôt sécuritaire, puis, espérons-le, prospère.</p>
<p>Et pourtant, vers la fin de la guerre, un homme avait bien réussi à la fois à négocier la paix et à brandir les armes. Symbole de force mais aussi de confiance, il n'était pas connu par son propre nom, mais par celui qu'on voulait bien lui donner : héros, champion, roi, etc. Un jour, son titre apparut sur les lèvres des soldats qui avaient vu ce guerrier mener les troupes près de la citadelle de fer : un empereur. Un roi parmi les rois. Un titre que seul le défunt Godrick aurait pu un jour convoiter, ou plutôt espérer mériter.</p>
<p>La grande guerre avait décimé les plus valeureux et expérimentés des dirigeants pouvant prétendre à un statut aussi important qu'unificateur. Avec la popularité grandissante du nouvel empereur, l'idée fut mise sur la table : rassembler tous les peuples de la grande guerre au sein d'une même institution, respectant les frontières et identités de chacun, et les protégeant d'une éventuelle guerre future.</p>
<p>L'Empire constitue depuis lors le plus grand territoire du monde connu, unissant presque tous les peuples autour d'un seul pouvoir, centralisé autour d'une monnaie, d'une armée, d'une administration et d'un homme : l'Empereur. Régissant les peuples alliés, il était l'autorité suprême du monde. Personnalité ambiguë : figure officielle mais mystérieuse, côtoyant les pouvoirs divins mais n'en faisant pas l'usage, décideur final mais s'impliquant le moins possible dans les affaires politiques...</p>
<p>Autour de l'Empereur, chaque peuple peut envoyer un représentant siéger à la citadelle impériale pour incarner les intérêts des siens. Les ambassadeurs des plus grandes nations ou les plus méritants peuvent accéder au statut de ministre. Les ministres forment le siège impérial et assistent l'Empereur dans la gestion de l'Empire, au détriment de la seule représentation de leur patrie ou de leurs intérêts personnels.</p>
<p>Le futur Empereur est un individu désigné par l'Empereur précédent, garantissant une continuité de la volonté de l'Empire et d'un règne cohérent. Si l'Empereur périt ou disparaît sans avoir désigné officiellement un successeur, alors la tâche incombe aux plus proches ministres de trouver un remplaçant. Le nouvel Empereur, étant un homme de confiance, fait le plus souvent partie du siège.</p>
<p>L'Empire est centralisé autour d'une ville-continent faisant office de capitale impériale, construite aux abords de la citadelle impériale. La capitale impériale regroupe les institutions commerciales, les ambassades, mais aussi de nombreuses auberges, des entrepôts gigantesques et divers commerces. Les plus grands artisans se sont installés ici pour bénéficier du flux de voyageurs et de la renommée qu'implique un tel emplacement.</p>
<p>Depuis l'instauration de l'Empire, les sciences et l'administration sont centralisées autour d'institutions impériales officielles :</p>
<p>Le calendrier impérial fixe son année 0 sur la fondation de la capitale, considéré comme la création officielle de l'Empire. Les chroniques de l'Empire consignent les événements les plus marquants de l'histoire connue.</p>
<p>Le commerce amorcé par les factions humaines pour réunir les continents fut fructueux, mais la diversité des guildes marchandes mena à la création de nombreuses monnaies. Ce faisant, les continents ne partageaient toujours pas de monnaie commune et étaient tout aussi distant qu'auparavant. Avec l'instauration d'une monnaie impériale, la couronne impériale, tous les peuples étaient unis économiquement malgré la distance.</p>
